[workspace]

members = [
    "bdk_chain",
    "bdk_cli_lib",
    "bdk_esplora_example",
    "bdk_electrum_example",
    "bdk_rpc_example",
    "bdk_tmp_plan",
    "bdk_coin_select",
    "bdk_cbf_example"
]
