[package]
name = "bdk_esplora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk_chain = { version = "0.2", features = ["serde", "miniscript"] }
esplora-client = { version = "0.3" }
